[pytest]
markers =
    smoke: Smoke tests
    regression: Regression tests
    critical: Critical path tests
    
addopts = 
    -v
    --alluredir=allure-results
    --clean-alluredir
    -p no:warnings
    
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
